//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Student
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Lname { get; set; }
        public string Class { get; set; }
        public Nullable<int> SchoolNumber { get; set; }
        public Nullable<int> TeacherId { get; set; }
        public virtual Teacher Teacher { get; set; }

    }
}
